openapi: 3.0.0
info:
  title: users
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /users:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      description: ''
      parameters: []
      requestBody: {}
components:
  schemas: {}
